### ISSUE TITLE
You hardcoded cuda

### ISSUE THREAD

**Issue by cchance27** [sipie800/ComfyUI-PuLID-Flux-Enhanced#12]
```
 cond = online_train(cond, device="cuda:1", step=train_step)
```

This breaks things on mac and others without cuda, and you forced it to :1 not everyone has a :1

**Comment by sipie800** [comment]
Thanks for pointing. The default device has been assigned to input device. Although I'm not sure without an additional cards the training is feasible since pulid flux take many VRAM itself. I will add device parameter in the future. But I never run big AI with MPS, I'm not sure if it is wise to support it.
